import Head from "next/head";
import Navbar from "../components/Navbar";
import { Children } from "react";
import styles from "../styles/Layout.module.css";

export default function Layout({ children }) {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>viktoredman.se</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <h1>Viktor Edman</h1>
        <Navbar />
        <main className={styles.main}>{children}</main>
      </div>
    </>
  );
}
